version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jobsearch
    ports:
      - "3306:3306"
    networks:
      - spring_mysql

  spring-boot-app:
    container_name: springbootapp
    # build . dockerfile cùng cấp và Name: thư mục chứa compose_tên service 
    build: .   
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobsearch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - spring_mysql

networks:
  spring_mysql:
    driver: bridge
